# -*- coding: utf-8 -*-
"""Updated_Proyek_Akhir_ML_Terapan_Dokumentasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACojEC587u1UWxDGmpS0lTOurfiHxKhq

# Sistem Rekomendasi
Dokumentasi proyek sistem rekomendasi ini menjelaskan setiap tahapan utama dalam membangun model collaborative filtering.

## 1. Pendahuluan
Proyek ini bertujuan untuk membangun sistem rekomendasi menggunakan pendekatan *collaborative filtering* dengan TensorFlow dan Keras. Sistem ini dirancang untuk merekomendasikan item berdasarkan interaksi pengguna sebelumnya.

## 2. Persiapan Data
Pada tahap ini, data yang digunakan diimpor dan dimuat untuk dianalisis. Data biasanya mencakup informasi pengguna, item, dan rating/interaksi antara keduanya.

## 3. Eksplorasi Data
Analisis awal dilakukan untuk memahami struktur dan distribusi data. Tahapan ini membantu dalam mengidentifikasi pola-pola umum, outlier, atau ketidakseimbangan dalam data.

## 4. Pra-pemrosesan Data
Data perlu disiapkan agar dapat digunakan oleh model. Ini mencakup konversi data ke format numerik, normalisasi, serta pembagian data menjadi data latih dan data uji.

## 5. Pembuatan Model Rekomendasi
Model collaborative filtering dibangun menggunakan TensorFlow dan Keras. Model ini dilatih menggunakan data latih untuk mempelajari representasi laten pengguna dan item.

## 6. Evaluasi Model
Model yang telah dilatih dievaluasi menggunakan metrik seperti MSE atau RMSE untuk menilai performanya dalam memprediksi rating atau interaksi.

## 7. Kesimpulan
Kesimpulan dibuat berdasarkan hasil evaluasi model. Bagian ini juga dapat mencakup saran untuk pengembangan sistem rekomendasi lebih lanjut.

### Data Understanding

Load dataset dari github
"""

import pandas as pd

drama = pd.read_csv('https://raw.githubusercontent.com/Meicha15/sistem_rekomen/refs/heads/main/korean_drama.csv')
review = pd.read_csv('https://raw.githubusercontent.com/Meicha15/sistem_rekomen/refs/heads/main/reviews.csv')
actors = pd.read_csv('https://raw.githubusercontent.com/Meicha15/sistem_rekomen/refs/heads/main/wiki_actors.csv')

"""Membaca ukuran masing masing data"""

print('Shape drama: ', drama.shape)
print('Shape review: ', review.shape)
print('Shape actors: ', actors.shape)

"""Mengetahui jumlah masing masing data"""

print('Jumlah drama: ', len(drama))
print('Jumlah review: ', len(review))
print('Jumlah actors: ', len(actors))

"""Melihat 5 teratas info dari masing masing data"""

print('Drama:')
display(drama.head())
print('\n Review\n')
display(review.head())
print('\n Actors\n')
display(actors.head())

"""### Univariate Exploratory Data Analysis

**Drama Variabel**

Melihat informasi dataset drama
"""

drama.info()

"""Melihat banyaknya dataset drama dan macam macam rating konten"""

print('Banyak data: ',len(drama.kdrama_id.unique()))
print('\nMacam rating konten: ', drama['content_rt'].unique())

"""Statistika deskriptif dari kolom 'year', 'tot_eps', 'duration', 'rank'"""

drama[['year', 'tot_eps', 'duration', 'rank']].describe()

"""Menghitung darimana drama berasal"""

drama['type'].value_counts()
drama['country'].value_counts()

"""Statistika deskriptif kolom 'synopsis'"""

drama['synopsis'].str.len().describe()

"""Mengecek duplikasi data dan missing value pada dataset drama"""

drama.duplicated().sum()
print('Jumlah duplikasi data: ', drama.duplicated().sum())

drama.isnull().sum()

"""Statistika deskriptif dataset drama"""

print('Statistika deskriptif drama:')
display(drama.describe(include='all'))

"""Visualisasi distribusi durasi drama.Tampak bahwa sebagian besar drama memiliki durasi sekitar 500-1500, dengan puncak lain di sekitar 3500-4500."""

import seaborn as sns
import matplotlib.pyplot as plt
sns.histplot(drama['duration'].dropna())
plt.title("Distribusi Durasi Drama")

"""Visualisasi jumlah drama pertahun diketahui bahwa paling banyak pada tahun 2021"""

plt.figure(figsize=(10, 4))
drama['year'].value_counts().sort_index().plot(kind='bar')
plt.title('Jumlah Drama per Tahun')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Drama')
plt.grid()
plt.show()

"""Visualisasi distribusi rating konten dengan rating konten pada 15++"""

drama['content_rt'].value_counts().plot(kind='bar', title='Distribusi Rating Konten')
plt.ylabel('Jumlah Drama')
plt.grid()
plt.show()

"""Visualisasi 10 jaringan terbanyak dengan drama ditayangkan paling banyak di Naver Tv Cast"""

drama['org_net'].value_counts().head(10).plot(kind='bar', title='10 Jaringan Penyiaran Terbanyak')
plt.ylabel('Jumlah Drama')
plt.grid()
plt.show()

"""Visualisasi distribusi total episode. Terlihat bahwa sebagian besar drama memiliki jumlah episode kurang dari 20, dengan puncak di sekitar 10-12 episode. Ini sesuai dengan format umum untuk mini series dan drama Korea."""

#Visualisasi distribusi total episode
plt.figure(figsize=(10, 4))
sns.histplot(drama['tot_eps'].dropna(), bins=20, kde=True)
plt.title('Distribusi Total Episode')
plt.xlabel('Jumlah Episode')
plt.grid()
plt.show()

"""**Review Variabel**

Melihat informasi dataset review
"""

review.info()

"""Statistika deskriptif dataset review"""

review.describe(include='all')

"""Mengecek duplikasi data dan missing value pada dataset review. Terlihat bahwa tidak ada duplikasi dan missing value"""

review.duplicated().sum()
print('Jumlah duplikasi data: ', review.duplicated().sum())

review.isnull().sum()

"""Visualisasi distribusi rating oleh pengguna menunjukkan rating tertinggi dan terbanyak ada di rating 10.0"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

plt.figure(figsize=(8, 4))
review['rating'] = review['overall_score']  # untuk konsistensi nama
review['rating'].value_counts().sort_index().plot(kind='bar')
plt.title('Distribusi Rating oleh Pengguna')
plt.xlabel('Rating')
plt.ylabel('Jumlah')
plt.xticks(rotation=0)
plt.grid()
plt.show()

"""Visualisasi distribusi rata rata skor tiap drama, rata rata berada di skor 8"""

avg_ratings = review.groupby('title')['overall_score'].mean()
plt.figure(figsize=(10, 4))
sns.histplot(avg_ratings, kde=True, bins=20)
plt.title('Distribusi Rata-rata Skor per Drama')
plt.xlabel('Rata-rata Skor')
plt.ylabel('Frekuensi')
plt.grid()
plt.show()

"""**Actor Variabel**

Melihat informasi dataset actors
"""

actors.info()

"""Melihat apa saja role atau posisi pemain yang ada pada dataset"""

print('Banyak role: ', actors['role'].unique())

"""Statistika deskriptif dataset actors"""

actors.describe(include='all')

"""Mengecek duplikasi dan missing value pada dataset aktor didapatkan tidak ada duplikasi dan missing value"""

#Cek duplikasi data
actors.duplicated().sum()
print('Jumlah duplikasi data: ', actors.duplicated().sum())

#Cek missing value
actors.isnull().sum()

"""Visualisasi distribusi peran aktor dengan peran paling banyak adalah main role"""

actors['role'].value_counts().plot(kind='bar', title='Distribusi Peran Aktor')
plt.ylabel('Jumlah Peran')
plt.grid()
plt.show()

"""Visualisasi aktor yang sering muncul yaitu Lee Yoo Jin"""

#Visualisasi aktor sering muncul
top_actors = actors['actor_name'].value_counts().head(10)
top_actors.plot(kind='barh', title='10 Aktor Terbanyak Muncul')
plt.xlabel('Jumlah Drama')
plt.grid()
plt.show()

"""### Data Preprocessing

### Penghapusan Duplikat
Menghapus entri duplikat dari masing-masing dataset (`drama`, `review`, `actors`) untuk menghindari redundansi data yang dapat mempengaruhi analisis.
"""

# Hapus duplikasi di ketiga dataset
drama.drop_duplicates(inplace=True)
review.drop_duplicates(inplace=True)
actors.drop_duplicates(inplace=True)

"""Melakukan penyalinan dataframe agar memudahkan, menghapus baris pada kolom dataset drama yang mengandung missing value. Menghapus kolom yang terlalu banyak missing value yaitu pada kolom 'director' dan 'screenwiter'. Setelahnya mereset index."""

drama_clean = drama.copy()
review_clean = review.copy()
actors_clean = actors.copy()

drama_clean['synopsis'] = drama_clean['synopsis'].fillna('')
drama_clean['aired_on'] = drama_clean['aired_on'].fillna('Unknown')
drama_clean['org_net'] = drama_clean['org_net'].fillna('Unknown')
drama_clean['duration'] = drama_clean['duration'].fillna(drama_clean['duration'].median())

drama_clean.drop(columns=['director', 'screenwriter'], inplace=True)

drama_clean.reset_index(drop=True, inplace=True)

# Review text kosong diisi string kosong
review_clean['review_text'] = review_clean['review_text'].fillna('')

# Reset index
review_clean.reset_index(drop=True, inplace=True)

"""Memastikan hanya review dari drama yang tersedia dan mencoba mmelihat contoh maksimal 100 review per drama jika tersedia."""

review_clean = review_clean[review_clean['title'].isin(drama_clean['drama_name'])]

review_per_drama = review_clean.groupby('title').apply(lambda x: x.sample(min(len(x), 100), random_state=42)).reset_index(drop=True)

"""**Menggabungkan DataFrame**

Menggabungkan dataset review dan dataset drama
"""

drama_review = pd.merge(review_per_drama, drama_clean, left_on='title', right_on='drama_name')

"""Melihat ukuran masing masing dan informasi pada DataFrame baru yaitu drama_review"""

print("drama_clean.shape:", drama_clean.shape)
print("review_clean.shape:", review_clean.shape)
print("drama_review.shape:", drama_review.shape)
drama_review.info()

"""Melihat 5 baris teratas dataframe drama_review"""

drama_review.head()

"""**Menggabungkan DataFrame dengan Actors**

Menggabungkan data drama_review dengan data actors berdasarkan kolom 'drama_name'
"""

full_data = pd.merge(drama_review, actors, on='drama_name', how='left')

# Cek hasilnya
print(full_data.shape)
full_data.info()

"""Melihat lima baris pertama DataFrame penggabungan"""

full_data.head()

"""Mengecek duplikasi data dan missing value terlihat bahwa tidak ada duplikasi data tetapi ada missing value"""

full_data.duplicated().sum()
print('Jumlah duplikasi data: ', full_data.duplicated().sum())

full_data.isnull().sum()

#Hapus missing value
full_data.dropna(inplace=True)

"""### Pembersihan String Nama Drama
Membersihkan kolom `drama_name` dengan menghapus spasi tambahan dan mengubah huruf menjadi huruf kecil agar seragam dan cocok antar dataset.
"""

drama_review['drama_name'] = drama_review['drama_name'].str.strip().str.lower()
actors['drama_name'] = actors['drama_name'].str.strip().str.lower()

full_data.info()

full_data.head()

"""### Model Development dengan Content Based Filtering"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""### Penghapusan Duplikat
Menghapus entri duplikat dari masing-masing dataset (`drama`, `review`, `actors`) untuk menghindari redundansi data yang dapat mempengaruhi analisis.
"""

# Gabungkan semua review dalam satu teks per drama
review_grouped = drama_review.groupby('drama_name')['review_text'].apply(lambda x: ' '.join(x.dropna())).reset_index()

# Gabungkan semua role/aktor dalam satu teks per drama
actor_grouped = actors.groupby('drama_name')['actor_name'].apply(lambda x: ' '.join(x.dropna())).reset_index()

# Gabungkan review + aktor berdasarkan 'drama_name'
drama_content = pd.merge(review_grouped, actor_grouped, on='drama_name', how='left')

# Tambahkan judul juga
drama_titles = drama_review[['drama_name', 'title', 'rating']].drop_duplicates()
drama_content = pd.merge(drama_content, drama_titles, on='drama_name', how='left')

# Buat kolom gabungan teks konten
drama_content['combined'] = drama_content['review_text'].fillna('') + ' ' + \
                            drama_content['actor_name'].fillna('') + ' ' + \
                            drama_content['title'].fillna('')
print(drama_content.columns)

"""### Penghapusan Duplikat
Menghapus entri duplikat dari masing-masing dataset (`drama`, `review`, `actors`) untuk menghindari redundansi data yang dapat mempengaruhi analisis.
"""

# Hapus duplikat berdasarkan drama_name
drama_content = drama_content.drop_duplicates(subset='drama_name', keep='first').reset_index(drop=True)

"""**TF-IDF Vectorizer dan Cosine Similarity**

Pada bagian ini, kita membangun model Content-Based Filtering dengan pendekatan berbasis teks menggunakan TF-IDF (Term Frequency-Inverse Document Frequency). Langkah-langkahnya:

- **TF-IDF Vectorizer** digunakan untuk mengubah teks dari kolom `combined` (gabungan fitur seperti judul, genre, dan deskripsi) menjadi representasi numerik (vektor).
- `stop_words='english'` membantu menghilangkan kata-kata umum (seperti "the", "and", dll) agar hasil lebih akurat.
- **Cosine Similarity** digunakan untuk menghitung kemiripan antara setiap drama berdasarkan vektor TF-IDF-nya.
- Mapping dari nama drama ke indeks dibuat menggunakan `pd.Series`, sehingga sistem dapat dengan cepat mencari posisi drama tertentu berdasarkan judulnya.

Langkah ini menjadi dasar untuk proses pencarian dan pemberian rekomendasi berdasarkan kemiripan konten antar drama.
"""

# TF-IDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(drama_content['combined'])

# Cosine similarity
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# Index mapping (judul -> index baris)
indices = pd.Series(drama_content.index, index=drama_content['drama_name'].str.lower())

"""**Mendapatkan Rekomendasi**

Fungsi `recommend(query, num_recommendations=5)` bertujuan untuk memberikan rekomendasi drama berdasarkan input pengguna, baik melalui judul drama maupun nama aktor. Berikut adalah penjelasan alur logikanya:

#### 1. Input Judul Drama
- Query (judul drama) diubah menjadi lowercase untuk mencocokkan dengan indeks (`indices`).
- Jika judul ditemukan:
  - Sistem mengambil indeks drama tersebut dari dataset.
  - Menghitung **cosine similarity** antara drama tersebut dan semua drama lain.
  - Drama yang sama (query itu sendiri) dihapus dari hasil.
  - Rekomendasi diurutkan berdasarkan skor kemiripan tertinggi.
  - Mengembalikan `num_recommendations` drama teratas beserta informasi: `drama_name`, `rating`, dan `actor_name`.

#### 2. Fallback: Jika Judul Tidak Ditemukan, Coba Nama Aktor
- Jika query tidak ditemukan sebagai judul:
  - Sistem mencoba mencocokkan query dengan nama aktor (`actor_name`).
  - Jika cocok:
    - Sistem mengambil drama lain dari aktor tersebut (selain yang sudah pernah ditampilkan) dan menampilkannya.
  - Jika tidak ditemukan juga, maka akan ditampilkan pesan:
    > "Judul drama atau nama aktor tidak ditemukan."

Fungsi ini fleksibel, karena mampu menangani input berupa nama drama atau nama aktor, dan memberikan rekomendasi alternatif jika data tidak ditemukan secara langsung.
"""

def recommend(query, num_recommendations=5):
    query = query.lower()

    idx = indices.get(query)

    if idx is not None:
        # Hitung similarity
        sim_scores = list(enumerate(cosine_sim[idx]))

        # Buang diri sendiri dari hasil rekomendasi
        sim_scores = [s for s in sim_scores if s[0] != idx]

        # Urutkan berdasarkan similarity
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

        # Ambil indeks drama teratas
        drama_indices = [i[0] for i in sim_scores[:num_recommendations]]

        return drama_content[['drama_name', 'rating', 'actor_name']].iloc[drama_indices]

    else:
        # Coba cari berdasarkan nama aktor
        actor_dramas = drama_content[drama_content['actor_name'].str.lower() == query]

        if actor_dramas.empty:
            return "Judul drama atau nama aktor tidak ditemukan."

        seen_titles = set(actor_dramas['drama_name'])
        other_dramas = drama_content[
            (drama_content['actor_name'].str.lower() == query) &
            (~drama_content['drama_name'].isin(seen_titles))
        ]

        return other_dramas[['drama_name', 'rating', 'actor_name']].head(num_recommendations)

"""### Contoh Rekomendasi Content-Based Filtering
Berikut adalah contoh hasil rekomendasi dari fungsi `recommend()` untuk judul 'Crash Landing on You'.
"""

drama_content[['drama_name', 'combined']].head()

recommend('Crash Landing on You', 3)

"""**Evaluasi**

Evaluasi dilakukan untuk mengukur seberapa relevan hasil rekomendasi yang diberikan oleh sistem. Salah satu metrik evaluasi yang digunakan adalah **Precision@K**, yang mengukur proporsi item relevan di antara K rekomendasi teratas.

#### Fungsi-fungsi yang digunakan:

- `get_relevant_items_by_rating()`:  
  Mengembalikan daftar nama drama dengan rating di atas ambang batas (`rating > 7`) sebagai item relevan.

- `recommend()`:  
  Memberikan rekomendasi drama berdasarkan judul input. Fungsi ini mengambil indeks drama dari query, menghitung cosine similarity, lalu mengembalikan nama-nama drama yang paling mirip.

- `precision_at_k()`:  
  Menghitung Precision@K berdasarkan jumlah item relevan yang muncul dalam `k` rekomendasi teratas. Jika tidak ada rekomendasi atau item relevan, maka precision dikembalikan sebagai `0.0`.

#### Contoh Evaluasi:

```python
query = "Crash Landing on You"
k = 3

recommended = recommend(query, k)
actual = get_relevant_items_by_rating(drama_content)

precision = precision_at_k(recommended, actual, k)
print(f"Precision@{k}: {precision:.2f}")
"""

def get_relevant_items_by_rating(df, rating_threshold=7):
    return df[df['rating'] > rating_threshold]['drama_name'].str.lower().tolist()

def recommend(query, num_recommendations=5):
    query = query.lower()
    if query not in indices:
        return []
    idx = indices[query]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:num_recommendations+1]
    drama_indices = [i[0] for i in sim_scores]
    return drama_content['drama_name'].iloc[drama_indices].str.lower().tolist()

def precision_at_k(recommended, actual, k):
    if not recommended or not actual:
        return 0.0
    return len([item for item in recommended[:k] if item in actual]) / k

# Input user
query = "Crash Landing on You"
k = 3

# Dapatkan rekomendasi dan item relevan
recommended_items = recommend(query, k)
relevant_items = get_relevant_items_by_rating(drama_content)

# Evaluasi
if recommended_items:
    precision = precision_at_k(recommended_items, relevant_items, k)
    print("Recommended items:", recommended_items)
    print("Relevant items:", relevant_items)
    print(f"Precision@{k}: {precision:.2f}")
else:
    print(f"Drama '{query}' tidak ditemukan dalam database.")

"""### Model Development dengan Collaborative Filtering

**Data Understanding**
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

"""Collaborative fitering menggunakan dataset review_clean"""

df = review_clean
df.head()

"""**Data Preparation**

Sebelum membangun model collaborative filtering, data perlu dipersiapkan dalam format numerik. Pada bagian ini:

- Dataset `review_clean` disalin dan hanya mengambil kolom penting: `user_id`, `title`, dan `overall_score`.
- **Encoding ID**:
  - Kolom `user_id` dan `title` diubah menjadi indeks numerik menggunakan `enumerate()`.
  - Mapping ini disimpan dalam dictionary `user_to_index` dan `title_to_index`.
  - Data asli kemudian di-*map* agar dapat digunakan dalam algoritma machine learning berbasis numerik.
"""

df = review_clean[['user_id', 'title', 'overall_score']].copy()

# Encode user dan item ke indeks numerik
user_ids = df['user_id'].unique().tolist()
title_ids = df['title'].unique().tolist()

user_to_index = {x: i for i, x in enumerate(user_ids)}
title_to_index = {x: i for i, x in enumerate(title_ids)}

df['user'] = df['user_id'].map(user_to_index)
df['title_id'] = df['title'].map(title_to_index)

"""- Fitur `X` terdiri dari dua kolom: `user` dan `title_id` (keduanya sudah dalam format numerik).
- Target `y` adalah `overall_score`, yaitu rating yang diberikan pengguna terhadap drama.
- Menggunakan `train_test_split` dari `sklearn`:
  - Membagi data menjadi 80% training dan 20% testing.
  - `random_state=42` digunakan untuk memastikan reprodusibilitas (hasil split konsisten setiap kali dijalankan).

Langkah ini merupakan persiapan penting sebelum model collaborative filtering dilatih.

**Membagi Data untuk Training dan Validasi**
"""

from sklearn.model_selection import train_test_split
X = df[['user', 'title_id']]
y = df['overall_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""### Proses Training

- **Input Layer**:
  - `user_input` menerima indeks user (dalam format numerik).
  - `title_input` menerima indeks judul drama.
- **Embedding Layer**:
  - Masing-masing input dipetakan ke vektor berdimensi 50 (`embedding_size`).
- **Flatten Layer**:
  - Vektor embedding diratakan (1D) untuk digunakan dalam operasi berikutnya.
- **Dot Product**:
  - Dot product antara vektor user dan vektor item digunakan untuk menangkap interaksi antara keduanya.
- **Dense Output Layer** *(opsional)*:
  - Tambahan layer dense untuk memberikan fleksibilitas pada output (dapat dihapus jika ingin langsung dari dot product).
- **Model Compilation**:
  - Optimizer: `adam`
  - Loss function: `mean squared error (MSE)`
  - Evaluation metric: `Root Mean Squared Error (RMSE)` untuk memantau akurasi prediksi skor.

Model ini efektif untuk memprediksi skor rating yang diberikan user terhadap drama berdasarkan pola interaksi sebelumnya, dan merupakan bentuk **matrix factorization yang dapat dilatih secara end-to-end**.
"""

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.metrics import RootMeanSquaredError

# Jumlah user dan title
n_users = len(user_ids)
n_titles = len(title_ids)
embedding_size = 50

# Input layer
user_input = keras.Input(shape=(1,))
title_input = keras.Input(shape=(1,))

# Embedding layer
user_embedding = layers.Embedding(input_dim=n_users, output_dim=embedding_size)(user_input)
title_embedding = layers.Embedding(input_dim=n_titles, output_dim=embedding_size)(title_input)

# Flatten embeddings
user_vec = layers.Flatten()(user_embedding)
title_vec = layers.Flatten()(title_embedding)

# Dot product
dot_product = layers.Dot(axes=1)([user_vec, title_vec])

# Optional Dense layer (boleh dihapus kalau mau output langsung dari dot_product)
output = layers.Dense(1)(dot_product)

# Model
model = keras.Model(inputs=[user_input, title_input], outputs=output)

# Compile dengan RMSE sebagai metrik tambahan
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=[RootMeanSquaredError()]
)

history = model.fit(
    [X_train['user'], X_train['title_id']], y_train,
    validation_data=([X_test['user'], X_test['title_id']], y_test),
    epochs=50,
    batch_size=32
)

"""**Visualisasi Metrik**

### Visualisasi Evaluasi RMSE
Menampilkan perkembangan nilai RMSE pada data training dan validation selama proses pelatihan model.
"""

#Visualisasi metrik RMSE
plt.plot(history.history['root_mean_squared_error'])
plt.plot(history.history['val_root_mean_squared_error'])
plt.title('model_metrics')
plt.ylabel('root_mean_squared_error')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

"""**Mendapatkan Rekomendasi**

Pada bagian ini dilakukan proses prediksi dan rekomendasi drama untuk satu pengguna berdasarkan model collaborative filtering yang telah dilatih.

#### Langkah-langkah:
1. **Pemilihan pengguna target**:
   - Diambil `user_id` pertama dari dataset sebagai contoh pengguna target.
   - User diubah ke indeks numerik (`user_to_index`) yang sesuai dengan model.

2. **Prediksi skor rating**:
   - Dibuat pasangan semua judul (`title_ids`) dengan user target.
   - Model memprediksi skor untuk semua judul drama yang tersedia.
   - Hasil prediksi kemudian diratakan menggunakan `.flatten()`.

3. **Menampilkan drama yang sudah pernah dirating oleh user**:
   - Filter drama yang sudah diberi rating oleh user target dari data asli.
   - Ditampilkan daftar drama tersebut dari skor tertinggi ke terendah.

4. **Menghasilkan rekomendasi**:
   - Judul-judul yang sudah dirating dikecualikan dari prediksi.
   - Dari sisa judul yang belum ditonton, diambil **10 skor tertinggi** berdasarkan hasil prediksi model.
   - Judul-judul tersebut ditampilkan sebagai rekomendasi.

Kode ini berguna untuk mengevaluasi performa sistem rekomendasi secara personal, sekaligus menunjukkan kemampuan model dalam menyarankan konten baru yang mungkin disukai pengguna.
"""

import numpy as np

# Pastikan df_cf didefinisikan dari data yang sudah dibersihkan
df_cf = df[['user_id', 'title', 'overall_score']].rename(columns={'overall_score': 'rating'})

# Pilih salah satu user (misal user pertama)
target_user_id = user_ids[0]
target_user_idx = user_to_index[target_user_id]

# Buat array prediksi untuk semua judul drama
all_title_indices = np.array([title_to_index[t] for t in title_ids])
user_array = np.full(len(all_title_indices), target_user_idx)

# Prediksi rating untuk semua drama
predictions = model.predict([user_array, all_title_indices]).flatten()

# Drama yang sudah diberi rating oleh user
user_rated = df_cf[df_cf['user_id'] == target_user_id]
user_rated_sorted = user_rated.sort_values(by='rating', ascending=False)

print(f"Testing recommendations for user_id: {target_user_id}\n")
print("Drama rated highly by user:")
print("-" * 40)
for _, row in user_rated_sorted.iterrows():
    print(f"{row['title']} | Rating: {row['rating']}")

# Ambil 10 rekomendasi tertinggi (yang belum ditonton user)
rated_titles = set(user_rated['title'])
unrated_indices = [i for i, t in enumerate(title_ids) if t not in rated_titles]

unrated_predictions = predictions[unrated_indices]
unrated_titles = [title_ids[i] for i in unrated_indices]

top_indices = np.argsort(unrated_predictions)[-10:][::-1]
top_titles = [unrated_titles[i] for i in top_indices]

print("\nTop 10 Drama Recommendations:")
print("-" * 40)
for title in top_titles:
    print(title)